services:
  metrics-db:
    container_name: metrics-db
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ssl-core
      DOCKER_INFLUXDB_INIT_PASSWORD: ssl-core
      DOCKER_INFLUXDB_INIT_ORG: ssl-core
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_RETENTION: 6h
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: metrics
    # volumes:
    #   - .influxdb/data:/var/lib/influxdb2
    #   - .influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    network_mode: "host"

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana
  #   # user: 1000:1000
  #   # volumes:
  #   #   - .grafana/data:/var/lib/grafana
  #   #   - .grafana/config:/etc/grafana/provisioning
  #   ports:
  #     - 3000:3000
  #   network_mode: "host"

  # metrics-ms:
  #   container-name: metrics-ms
  #   build:
  #     context: .
  #     dockerfile: metrics-ms/metrics-sherlock/metrics-sherlock.Dockerfile
  #   volumes:
  #     - .ssl-core:/tmp/.ssl-core
  #   # ports:
  #     # - ...
  #   network_mode: "host"

networks:
  default:
    name: "host"
    external: true
