version: "3"
services:
  service-example:
    build:
      context: .
      dockerfile: tester/.devcontainer/Dockerfile
      args:
        - SOURCE_DIRECTORY=gateway/gateway-augusto
    working_dir: /workspaces/gateway/gateway-augusto
    container_name: client
    command: ["bin/client_main"]
    volumes:
      - /tmp:/tmp
    ports:
      - 8082:8082
