// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/common/game_command.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*GameCommand_Halt_
	//	*GameCommand_InGame_
	//	*GameCommand_Stop_
	//	*GameCommand_HomeBallPlacement
	//	*GameCommand_AwayBallPlacement
	//	*GameCommand_HomePrepareKickoff
	//	*GameCommand_AwayPrepareKickoff
	//	*GameCommand_HomeKickoff
	//	*GameCommand_AwayKickoff
	//	*GameCommand_HomePreparePenalty
	//	*GameCommand_AwayPreparePenalty
	//	*GameCommand_HomePenalty
	//	*GameCommand_AwayPenalty
	//	*GameCommand_HomePrepareDirectFreeKick
	//	*GameCommand_AwayPrepareDirectFreeKick
	//	*GameCommand_HomeDirectFreeKick
	//	*GameCommand_AwayDirectFreeKick
	//	*GameCommand_HomeTimeout
	//	*GameCommand_AwayTimeout
	//	*GameCommand_Interval_
	Command isGameCommand_Command `protobuf_oneof:"command"`
}

func (x *GameCommand) Reset() {
	*x = GameCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand) ProtoMessage() {}

func (x *GameCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand.ProtoReflect.Descriptor instead.
func (*GameCommand) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0}
}

func (m *GameCommand) GetCommand() isGameCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *GameCommand) GetHalt() *GameCommand_Halt {
	if x, ok := x.GetCommand().(*GameCommand_Halt_); ok {
		return x.Halt
	}
	return nil
}

func (x *GameCommand) GetInGame() *GameCommand_InGame {
	if x, ok := x.GetCommand().(*GameCommand_InGame_); ok {
		return x.InGame
	}
	return nil
}

func (x *GameCommand) GetStop() *GameCommand_Stop {
	if x, ok := x.GetCommand().(*GameCommand_Stop_); ok {
		return x.Stop
	}
	return nil
}

func (x *GameCommand) GetHomeBallPlacement() *GameCommand_BallPlacement {
	if x, ok := x.GetCommand().(*GameCommand_HomeBallPlacement); ok {
		return x.HomeBallPlacement
	}
	return nil
}

func (x *GameCommand) GetAwayBallPlacement() *GameCommand_BallPlacement {
	if x, ok := x.GetCommand().(*GameCommand_AwayBallPlacement); ok {
		return x.AwayBallPlacement
	}
	return nil
}

func (x *GameCommand) GetHomePrepareKickoff() *GameCommand_PrepareKickoff {
	if x, ok := x.GetCommand().(*GameCommand_HomePrepareKickoff); ok {
		return x.HomePrepareKickoff
	}
	return nil
}

func (x *GameCommand) GetAwayPrepareKickoff() *GameCommand_PrepareKickoff {
	if x, ok := x.GetCommand().(*GameCommand_AwayPrepareKickoff); ok {
		return x.AwayPrepareKickoff
	}
	return nil
}

func (x *GameCommand) GetHomeKickoff() *GameCommand_Kickoff {
	if x, ok := x.GetCommand().(*GameCommand_HomeKickoff); ok {
		return x.HomeKickoff
	}
	return nil
}

func (x *GameCommand) GetAwayKickoff() *GameCommand_Kickoff {
	if x, ok := x.GetCommand().(*GameCommand_AwayKickoff); ok {
		return x.AwayKickoff
	}
	return nil
}

func (x *GameCommand) GetHomePreparePenalty() *GameCommand_PreparePenalty {
	if x, ok := x.GetCommand().(*GameCommand_HomePreparePenalty); ok {
		return x.HomePreparePenalty
	}
	return nil
}

func (x *GameCommand) GetAwayPreparePenalty() *GameCommand_PreparePenalty {
	if x, ok := x.GetCommand().(*GameCommand_AwayPreparePenalty); ok {
		return x.AwayPreparePenalty
	}
	return nil
}

func (x *GameCommand) GetHomePenalty() *GameCommand_Penalty {
	if x, ok := x.GetCommand().(*GameCommand_HomePenalty); ok {
		return x.HomePenalty
	}
	return nil
}

func (x *GameCommand) GetAwayPenalty() *GameCommand_Penalty {
	if x, ok := x.GetCommand().(*GameCommand_AwayPenalty); ok {
		return x.AwayPenalty
	}
	return nil
}

func (x *GameCommand) GetHomePrepareDirectFreeKick() *GameCommand_PrepareDirectFreeKick {
	if x, ok := x.GetCommand().(*GameCommand_HomePrepareDirectFreeKick); ok {
		return x.HomePrepareDirectFreeKick
	}
	return nil
}

func (x *GameCommand) GetAwayPrepareDirectFreeKick() *GameCommand_PrepareDirectFreeKick {
	if x, ok := x.GetCommand().(*GameCommand_AwayPrepareDirectFreeKick); ok {
		return x.AwayPrepareDirectFreeKick
	}
	return nil
}

func (x *GameCommand) GetHomeDirectFreeKick() *GameCommand_DirectFreeKick {
	if x, ok := x.GetCommand().(*GameCommand_HomeDirectFreeKick); ok {
		return x.HomeDirectFreeKick
	}
	return nil
}

func (x *GameCommand) GetAwayDirectFreeKick() *GameCommand_DirectFreeKick {
	if x, ok := x.GetCommand().(*GameCommand_AwayDirectFreeKick); ok {
		return x.AwayDirectFreeKick
	}
	return nil
}

func (x *GameCommand) GetHomeTimeout() *GameCommand_Timeout {
	if x, ok := x.GetCommand().(*GameCommand_HomeTimeout); ok {
		return x.HomeTimeout
	}
	return nil
}

func (x *GameCommand) GetAwayTimeout() *GameCommand_Timeout {
	if x, ok := x.GetCommand().(*GameCommand_AwayTimeout); ok {
		return x.AwayTimeout
	}
	return nil
}

func (x *GameCommand) GetInterval() *GameCommand_Interval {
	if x, ok := x.GetCommand().(*GameCommand_Interval_); ok {
		return x.Interval
	}
	return nil
}

type isGameCommand_Command interface {
	isGameCommand_Command()
}

type GameCommand_Halt_ struct {
	Halt *GameCommand_Halt `protobuf:"bytes,1,opt,name=halt,proto3,oneof"`
}

type GameCommand_InGame_ struct {
	InGame *GameCommand_InGame `protobuf:"bytes,2,opt,name=in_game,json=inGame,proto3,oneof"`
}

type GameCommand_Stop_ struct {
	Stop *GameCommand_Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type GameCommand_HomeBallPlacement struct {
	HomeBallPlacement *GameCommand_BallPlacement `protobuf:"bytes,4,opt,name=home_ball_placement,json=homeBallPlacement,proto3,oneof"`
}

type GameCommand_AwayBallPlacement struct {
	AwayBallPlacement *GameCommand_BallPlacement `protobuf:"bytes,5,opt,name=away_ball_placement,json=awayBallPlacement,proto3,oneof"`
}

type GameCommand_HomePrepareKickoff struct {
	HomePrepareKickoff *GameCommand_PrepareKickoff `protobuf:"bytes,6,opt,name=home_prepare_kickoff,json=homePrepareKickoff,proto3,oneof"`
}

type GameCommand_AwayPrepareKickoff struct {
	AwayPrepareKickoff *GameCommand_PrepareKickoff `protobuf:"bytes,7,opt,name=away_prepare_kickoff,json=awayPrepareKickoff,proto3,oneof"`
}

type GameCommand_HomeKickoff struct {
	HomeKickoff *GameCommand_Kickoff `protobuf:"bytes,8,opt,name=home_kickoff,json=homeKickoff,proto3,oneof"`
}

type GameCommand_AwayKickoff struct {
	AwayKickoff *GameCommand_Kickoff `protobuf:"bytes,9,opt,name=away_kickoff,json=awayKickoff,proto3,oneof"`
}

type GameCommand_HomePreparePenalty struct {
	HomePreparePenalty *GameCommand_PreparePenalty `protobuf:"bytes,10,opt,name=home_prepare_penalty,json=homePreparePenalty,proto3,oneof"`
}

type GameCommand_AwayPreparePenalty struct {
	AwayPreparePenalty *GameCommand_PreparePenalty `protobuf:"bytes,11,opt,name=away_prepare_penalty,json=awayPreparePenalty,proto3,oneof"`
}

type GameCommand_HomePenalty struct {
	HomePenalty *GameCommand_Penalty `protobuf:"bytes,12,opt,name=home_penalty,json=homePenalty,proto3,oneof"`
}

type GameCommand_AwayPenalty struct {
	AwayPenalty *GameCommand_Penalty `protobuf:"bytes,13,opt,name=away_penalty,json=awayPenalty,proto3,oneof"`
}

type GameCommand_HomePrepareDirectFreeKick struct {
	HomePrepareDirectFreeKick *GameCommand_PrepareDirectFreeKick `protobuf:"bytes,14,opt,name=home_prepare_direct_free_kick,json=homePrepareDirectFreeKick,proto3,oneof"`
}

type GameCommand_AwayPrepareDirectFreeKick struct {
	AwayPrepareDirectFreeKick *GameCommand_PrepareDirectFreeKick `protobuf:"bytes,15,opt,name=away_prepare_direct_free_kick,json=awayPrepareDirectFreeKick,proto3,oneof"`
}

type GameCommand_HomeDirectFreeKick struct {
	HomeDirectFreeKick *GameCommand_DirectFreeKick `protobuf:"bytes,16,opt,name=home_direct_free_kick,json=homeDirectFreeKick,proto3,oneof"`
}

type GameCommand_AwayDirectFreeKick struct {
	AwayDirectFreeKick *GameCommand_DirectFreeKick `protobuf:"bytes,17,opt,name=away_direct_free_kick,json=awayDirectFreeKick,proto3,oneof"`
}

type GameCommand_HomeTimeout struct {
	HomeTimeout *GameCommand_Timeout `protobuf:"bytes,18,opt,name=home_timeout,json=homeTimeout,proto3,oneof"`
}

type GameCommand_AwayTimeout struct {
	AwayTimeout *GameCommand_Timeout `protobuf:"bytes,19,opt,name=away_timeout,json=awayTimeout,proto3,oneof"`
}

type GameCommand_Interval_ struct {
	Interval *GameCommand_Interval `protobuf:"bytes,20,opt,name=interval,proto3,oneof"`
}

func (*GameCommand_Halt_) isGameCommand_Command() {}

func (*GameCommand_InGame_) isGameCommand_Command() {}

func (*GameCommand_Stop_) isGameCommand_Command() {}

func (*GameCommand_HomeBallPlacement) isGameCommand_Command() {}

func (*GameCommand_AwayBallPlacement) isGameCommand_Command() {}

func (*GameCommand_HomePrepareKickoff) isGameCommand_Command() {}

func (*GameCommand_AwayPrepareKickoff) isGameCommand_Command() {}

func (*GameCommand_HomeKickoff) isGameCommand_Command() {}

func (*GameCommand_AwayKickoff) isGameCommand_Command() {}

func (*GameCommand_HomePreparePenalty) isGameCommand_Command() {}

func (*GameCommand_AwayPreparePenalty) isGameCommand_Command() {}

func (*GameCommand_HomePenalty) isGameCommand_Command() {}

func (*GameCommand_AwayPenalty) isGameCommand_Command() {}

func (*GameCommand_HomePrepareDirectFreeKick) isGameCommand_Command() {}

func (*GameCommand_AwayPrepareDirectFreeKick) isGameCommand_Command() {}

func (*GameCommand_HomeDirectFreeKick) isGameCommand_Command() {}

func (*GameCommand_AwayDirectFreeKick) isGameCommand_Command() {}

func (*GameCommand_HomeTimeout) isGameCommand_Command() {}

func (*GameCommand_AwayTimeout) isGameCommand_Command() {}

func (*GameCommand_Interval_) isGameCommand_Command() {}

type GameCommand_Halt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_Halt) Reset() {
	*x = GameCommand_Halt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Halt) ProtoMessage() {}

func (x *GameCommand_Halt) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Halt.ProtoReflect.Descriptor instead.
func (*GameCommand_Halt) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 0}
}

type GameCommand_InGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_InGame) Reset() {
	*x = GameCommand_InGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_InGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_InGame) ProtoMessage() {}

func (x *GameCommand_InGame) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_InGame.ProtoReflect.Descriptor instead.
func (*GameCommand_InGame) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 1}
}

type GameCommand_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_Stop) Reset() {
	*x = GameCommand_Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Stop) ProtoMessage() {}

func (x *GameCommand_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Stop.ProtoReflect.Descriptor instead.
func (*GameCommand_Stop) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 2}
}

type GameCommand_BallPlacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position      *Point2Df            `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	RemainingTime *durationpb.Duration `protobuf:"bytes,2,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *GameCommand_BallPlacement) Reset() {
	*x = GameCommand_BallPlacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_BallPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_BallPlacement) ProtoMessage() {}

func (x *GameCommand_BallPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_BallPlacement.ProtoReflect.Descriptor instead.
func (*GameCommand_BallPlacement) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 3}
}

func (x *GameCommand_BallPlacement) GetPosition() *Point2Df {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GameCommand_BallPlacement) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

type GameCommand_PrepareKickoff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_PrepareKickoff) Reset() {
	*x = GameCommand_PrepareKickoff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_PrepareKickoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_PrepareKickoff) ProtoMessage() {}

func (x *GameCommand_PrepareKickoff) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_PrepareKickoff.ProtoReflect.Descriptor instead.
func (*GameCommand_PrepareKickoff) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 4}
}

type GameCommand_Kickoff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainingTime *durationpb.Duration `protobuf:"bytes,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *GameCommand_Kickoff) Reset() {
	*x = GameCommand_Kickoff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Kickoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Kickoff) ProtoMessage() {}

func (x *GameCommand_Kickoff) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Kickoff.ProtoReflect.Descriptor instead.
func (*GameCommand_Kickoff) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 5}
}

func (x *GameCommand_Kickoff) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

type GameCommand_PreparePenalty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_PreparePenalty) Reset() {
	*x = GameCommand_PreparePenalty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_PreparePenalty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_PreparePenalty) ProtoMessage() {}

func (x *GameCommand_PreparePenalty) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_PreparePenalty.ProtoReflect.Descriptor instead.
func (*GameCommand_PreparePenalty) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 6}
}

type GameCommand_Penalty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainingTime *durationpb.Duration `protobuf:"bytes,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *GameCommand_Penalty) Reset() {
	*x = GameCommand_Penalty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Penalty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Penalty) ProtoMessage() {}

func (x *GameCommand_Penalty) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Penalty.ProtoReflect.Descriptor instead.
func (*GameCommand_Penalty) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 7}
}

func (x *GameCommand_Penalty) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

type GameCommand_PrepareDirectFreeKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_PrepareDirectFreeKick) Reset() {
	*x = GameCommand_PrepareDirectFreeKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_PrepareDirectFreeKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_PrepareDirectFreeKick) ProtoMessage() {}

func (x *GameCommand_PrepareDirectFreeKick) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_PrepareDirectFreeKick.ProtoReflect.Descriptor instead.
func (*GameCommand_PrepareDirectFreeKick) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 8}
}

type GameCommand_DirectFreeKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainingTime *durationpb.Duration `protobuf:"bytes,1,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *GameCommand_DirectFreeKick) Reset() {
	*x = GameCommand_DirectFreeKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_DirectFreeKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_DirectFreeKick) ProtoMessage() {}

func (x *GameCommand_DirectFreeKick) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_DirectFreeKick.ProtoReflect.Descriptor instead.
func (*GameCommand_DirectFreeKick) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 9}
}

func (x *GameCommand_DirectFreeKick) GetRemainingTime() *durationpb.Duration {
	if x != nil {
		return x.RemainingTime
	}
	return nil
}

type GameCommand_Timeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_Timeout) Reset() {
	*x = GameCommand_Timeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Timeout) ProtoMessage() {}

func (x *GameCommand_Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Timeout.ProtoReflect.Descriptor instead.
func (*GameCommand_Timeout) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 10}
}

type GameCommand_Interval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameCommand_Interval) Reset() {
	*x = GameCommand_Interval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_common_game_command_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCommand_Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCommand_Interval) ProtoMessage() {}

func (x *GameCommand_Interval) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_common_game_command_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCommand_Interval.ProtoReflect.Descriptor instead.
func (*GameCommand_Interval) Descriptor() ([]byte, []int) {
	return file_protocols_common_game_command_proto_rawDescGZIP(), []int{0, 11}
}

var File_protocols_common_game_command_proto protoreflect.FileDescriptor

var file_protocols_common_game_command_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x11, 0x0a, 0x0b, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x68, 0x61, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x48, 0x61, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61,
	0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x5d, 0x0a,
	0x13, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x62, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x68, 0x6f, 0x6d, 0x65, 0x42,
	0x61, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x13,
	0x61, 0x77, 0x61, 0x79, 0x5f, 0x62, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x61, 0x77, 0x61, 0x79, 0x42, 0x61,
	0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x60, 0x0a, 0x14, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x6b, 0x69, 0x63, 0x6b,
	0x6f, 0x66, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x48, 0x00, 0x52, 0x12, 0x68, 0x6f, 0x6d, 0x65, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x60, 0x0a,
	0x14, 0x61, 0x77, 0x61, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x6b, 0x69,
	0x63, 0x6b, 0x6f, 0x66, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x48, 0x00, 0x52, 0x12, 0x61, 0x77, 0x61,
	0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12,
	0x4a, 0x0a, 0x0c, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x6b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x48, 0x00, 0x52, 0x0b,
	0x68, 0x6f, 0x6d, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x4a, 0x0a, 0x0c, 0x61,
	0x77, 0x61, 0x79, 0x5f, 0x6b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x77, 0x61, 0x79,
	0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x60, 0x0a, 0x14, 0x68, 0x6f, 0x6d, 0x65, 0x5f,
	0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x50, 0x65, 0x6e, 0x61,
	0x6c, 0x74, 0x79, 0x48, 0x00, 0x52, 0x12, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x60, 0x0a, 0x14, 0x61, 0x77, 0x61,
	0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74,
	0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x50, 0x65,
	0x6e, 0x61, 0x6c, 0x74, 0x79, 0x48, 0x00, 0x52, 0x12, 0x61, 0x77, 0x61, 0x79, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0c, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x68, 0x6f, 0x6d, 0x65,
	0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x0c, 0x61, 0x77, 0x61, 0x79, 0x5f,
	0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x65, 0x6e,
	0x61, 0x6c, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x77, 0x61, 0x79, 0x50, 0x65, 0x6e, 0x61,
	0x6c, 0x74, 0x79, 0x12, 0x77, 0x0a, 0x1d, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x5f,
	0x6b, 0x69, 0x63, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x48,
	0x00, 0x52, 0x19, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x77, 0x0a, 0x1d,
	0x61, 0x77, 0x61, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x5f, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x6b, 0x69, 0x63, 0x6b, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x19, 0x61, 0x77, 0x61, 0x79,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x46, 0x72, 0x65,
	0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x61, 0x0a, 0x15, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x6b, 0x69, 0x63, 0x6b, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x46, 0x72, 0x65, 0x65, 0x4b, 0x69,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x12, 0x68, 0x6f, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x61, 0x0a, 0x15, 0x61, 0x77, 0x61, 0x79,
	0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x6b, 0x69, 0x63,
	0x6b, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x46, 0x72, 0x65,
	0x65, 0x4b, 0x69, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x12, 0x61, 0x77, 0x61, 0x79, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x4a, 0x0a, 0x0c, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x68, 0x6f, 0x6d, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x4a, 0x0a, 0x0c, 0x61, 0x77, 0x61, 0x79, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x77, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x44, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x1a, 0x06, 0x0a, 0x04, 0x48, 0x61, 0x6c,
	0x74, 0x1a, 0x08, 0x0a, 0x06, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x1a, 0x06, 0x0a, 0x04, 0x53,
	0x74, 0x6f, 0x70, 0x1a, 0x89, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x32, 0x44, 0x66, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a,
	0x0e, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0d, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x1a,
	0x10, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66,
	0x66, 0x1a, 0x4b, 0x0a, 0x07, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x12, 0x40, 0x0a, 0x0e,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0d, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x10,
	0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79,
	0x1a, 0x4b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0e, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x17, 0x0a,
	0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x46, 0x72,
	0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x1a, 0x52, 0x0a, 0x0e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x46, 0x72, 0x65, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_common_game_command_proto_rawDescOnce sync.Once
	file_protocols_common_game_command_proto_rawDescData = file_protocols_common_game_command_proto_rawDesc
)

func file_protocols_common_game_command_proto_rawDescGZIP() []byte {
	file_protocols_common_game_command_proto_rawDescOnce.Do(func() {
		file_protocols_common_game_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_common_game_command_proto_rawDescData)
	})
	return file_protocols_common_game_command_proto_rawDescData
}

var file_protocols_common_game_command_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protocols_common_game_command_proto_goTypes = []interface{}{
	(*GameCommand)(nil),                       // 0: protocols.common.GameCommand
	(*GameCommand_Halt)(nil),                  // 1: protocols.common.GameCommand.Halt
	(*GameCommand_InGame)(nil),                // 2: protocols.common.GameCommand.InGame
	(*GameCommand_Stop)(nil),                  // 3: protocols.common.GameCommand.Stop
	(*GameCommand_BallPlacement)(nil),         // 4: protocols.common.GameCommand.BallPlacement
	(*GameCommand_PrepareKickoff)(nil),        // 5: protocols.common.GameCommand.PrepareKickoff
	(*GameCommand_Kickoff)(nil),               // 6: protocols.common.GameCommand.Kickoff
	(*GameCommand_PreparePenalty)(nil),        // 7: protocols.common.GameCommand.PreparePenalty
	(*GameCommand_Penalty)(nil),               // 8: protocols.common.GameCommand.Penalty
	(*GameCommand_PrepareDirectFreeKick)(nil), // 9: protocols.common.GameCommand.PrepareDirectFreeKick
	(*GameCommand_DirectFreeKick)(nil),        // 10: protocols.common.GameCommand.DirectFreeKick
	(*GameCommand_Timeout)(nil),               // 11: protocols.common.GameCommand.Timeout
	(*GameCommand_Interval)(nil),              // 12: protocols.common.GameCommand.Interval
	(*Point2Df)(nil),                          // 13: protocols.common.Point2Df
	(*durationpb.Duration)(nil),               // 14: google.protobuf.Duration
}
var file_protocols_common_game_command_proto_depIdxs = []int32{
	1,  // 0: protocols.common.GameCommand.halt:type_name -> protocols.common.GameCommand.Halt
	2,  // 1: protocols.common.GameCommand.in_game:type_name -> protocols.common.GameCommand.InGame
	3,  // 2: protocols.common.GameCommand.stop:type_name -> protocols.common.GameCommand.Stop
	4,  // 3: protocols.common.GameCommand.home_ball_placement:type_name -> protocols.common.GameCommand.BallPlacement
	4,  // 4: protocols.common.GameCommand.away_ball_placement:type_name -> protocols.common.GameCommand.BallPlacement
	5,  // 5: protocols.common.GameCommand.home_prepare_kickoff:type_name -> protocols.common.GameCommand.PrepareKickoff
	5,  // 6: protocols.common.GameCommand.away_prepare_kickoff:type_name -> protocols.common.GameCommand.PrepareKickoff
	6,  // 7: protocols.common.GameCommand.home_kickoff:type_name -> protocols.common.GameCommand.Kickoff
	6,  // 8: protocols.common.GameCommand.away_kickoff:type_name -> protocols.common.GameCommand.Kickoff
	7,  // 9: protocols.common.GameCommand.home_prepare_penalty:type_name -> protocols.common.GameCommand.PreparePenalty
	7,  // 10: protocols.common.GameCommand.away_prepare_penalty:type_name -> protocols.common.GameCommand.PreparePenalty
	8,  // 11: protocols.common.GameCommand.home_penalty:type_name -> protocols.common.GameCommand.Penalty
	8,  // 12: protocols.common.GameCommand.away_penalty:type_name -> protocols.common.GameCommand.Penalty
	9,  // 13: protocols.common.GameCommand.home_prepare_direct_free_kick:type_name -> protocols.common.GameCommand.PrepareDirectFreeKick
	9,  // 14: protocols.common.GameCommand.away_prepare_direct_free_kick:type_name -> protocols.common.GameCommand.PrepareDirectFreeKick
	10, // 15: protocols.common.GameCommand.home_direct_free_kick:type_name -> protocols.common.GameCommand.DirectFreeKick
	10, // 16: protocols.common.GameCommand.away_direct_free_kick:type_name -> protocols.common.GameCommand.DirectFreeKick
	11, // 17: protocols.common.GameCommand.home_timeout:type_name -> protocols.common.GameCommand.Timeout
	11, // 18: protocols.common.GameCommand.away_timeout:type_name -> protocols.common.GameCommand.Timeout
	12, // 19: protocols.common.GameCommand.interval:type_name -> protocols.common.GameCommand.Interval
	13, // 20: protocols.common.GameCommand.BallPlacement.position:type_name -> protocols.common.Point2Df
	14, // 21: protocols.common.GameCommand.BallPlacement.remaining_time:type_name -> google.protobuf.Duration
	14, // 22: protocols.common.GameCommand.Kickoff.remaining_time:type_name -> google.protobuf.Duration
	14, // 23: protocols.common.GameCommand.Penalty.remaining_time:type_name -> google.protobuf.Duration
	14, // 24: protocols.common.GameCommand.DirectFreeKick.remaining_time:type_name -> google.protobuf.Duration
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_protocols_common_game_command_proto_init() }
func file_protocols_common_game_command_proto_init() {
	if File_protocols_common_game_command_proto != nil {
		return
	}
	file_protocols_common_geometry_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protocols_common_game_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Halt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_InGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_BallPlacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_PrepareKickoff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Kickoff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_PreparePenalty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Penalty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_PrepareDirectFreeKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_DirectFreeKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Timeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_common_game_command_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCommand_Interval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocols_common_game_command_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GameCommand_Halt_)(nil),
		(*GameCommand_InGame_)(nil),
		(*GameCommand_Stop_)(nil),
		(*GameCommand_HomeBallPlacement)(nil),
		(*GameCommand_AwayBallPlacement)(nil),
		(*GameCommand_HomePrepareKickoff)(nil),
		(*GameCommand_AwayPrepareKickoff)(nil),
		(*GameCommand_HomeKickoff)(nil),
		(*GameCommand_AwayKickoff)(nil),
		(*GameCommand_HomePreparePenalty)(nil),
		(*GameCommand_AwayPreparePenalty)(nil),
		(*GameCommand_HomePenalty)(nil),
		(*GameCommand_AwayPenalty)(nil),
		(*GameCommand_HomePrepareDirectFreeKick)(nil),
		(*GameCommand_AwayPrepareDirectFreeKick)(nil),
		(*GameCommand_HomeDirectFreeKick)(nil),
		(*GameCommand_AwayDirectFreeKick)(nil),
		(*GameCommand_HomeTimeout)(nil),
		(*GameCommand_AwayTimeout)(nil),
		(*GameCommand_Interval_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_common_game_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_common_game_command_proto_goTypes,
		DependencyIndexes: file_protocols_common_game_command_proto_depIdxs,
		MessageInfos:      file_protocols_common_game_command_proto_msgTypes,
	}.Build()
	File_protocols_common_game_command_proto = out.File
	file_protocols_common_game_command_proto_rawDesc = nil
	file_protocols_common_game_command_proto_goTypes = nil
	file_protocols_common_game_command_proto_depIdxs = nil
}
