// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/common/match_type.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchType int32

const (
	MatchType_MATCH_TYPE_UNSPECIFIED       MatchType = 0
	MatchType_MATCH_TYPE_GROUP_PHASE       MatchType = 1
	MatchType_MATCH_TYPE_ELIMINATION_PHASE MatchType = 2
	MatchType_MATCH_TYPE_FRIENDLY          MatchType = 3
)

// Enum value maps for MatchType.
var (
	MatchType_name = map[int32]string{
		0: "MATCH_TYPE_UNSPECIFIED",
		1: "MATCH_TYPE_GROUP_PHASE",
		2: "MATCH_TYPE_ELIMINATION_PHASE",
		3: "MATCH_TYPE_FRIENDLY",
	}
	MatchType_value = map[string]int32{
		"MATCH_TYPE_UNSPECIFIED":       0,
		"MATCH_TYPE_GROUP_PHASE":       1,
		"MATCH_TYPE_ELIMINATION_PHASE": 2,
		"MATCH_TYPE_FRIENDLY":          3,
	}
)

func (x MatchType) Enum() *MatchType {
	p := new(MatchType)
	*p = x
	return p
}

func (x MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_common_match_type_proto_enumTypes[0].Descriptor()
}

func (MatchType) Type() protoreflect.EnumType {
	return &file_protocols_common_match_type_proto_enumTypes[0]
}

func (x MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchType.Descriptor instead.
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return file_protocols_common_match_type_proto_rawDescGZIP(), []int{0}
}

var File_protocols_common_match_type_proto protoreflect.FileDescriptor

var file_protocols_common_match_type_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x7e, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a,
	0x0a, 0x16, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x41,
	0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4c, 0x49, 0x4d, 0x49, 0x4e, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x48, 0x41, 0x53, 0x45, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x52, 0x49, 0x45, 0x4e,
	0x44, 0x4c, 0x59, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_common_match_type_proto_rawDescOnce sync.Once
	file_protocols_common_match_type_proto_rawDescData = file_protocols_common_match_type_proto_rawDesc
)

func file_protocols_common_match_type_proto_rawDescGZIP() []byte {
	file_protocols_common_match_type_proto_rawDescOnce.Do(func() {
		file_protocols_common_match_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_common_match_type_proto_rawDescData)
	})
	return file_protocols_common_match_type_proto_rawDescData
}

var file_protocols_common_match_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocols_common_match_type_proto_goTypes = []interface{}{
	(MatchType)(0), // 0: protocols.common.MatchType
}
var file_protocols_common_match_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocols_common_match_type_proto_init() }
func file_protocols_common_match_type_proto_init() {
	if File_protocols_common_match_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_common_match_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_common_match_type_proto_goTypes,
		DependencyIndexes: file_protocols_common_match_type_proto_depIdxs,
		EnumInfos:         file_protocols_common_match_type_proto_enumTypes,
	}.Build()
	File_protocols_common_match_type_proto = out.File
	file_protocols_common_match_type_proto_rawDesc = nil
	file_protocols_common_match_type_proto_goTypes = nil
	file_protocols_common_match_type_proto_depIdxs = nil
}
