// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/common/team.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team int32

const (
	Team_TEAM_UNSPECIFIED Team = 0
	Team_TEAM_HOME        Team = 1
	Team_TEAM_AWAY        Team = 2
)

// Enum value maps for Team.
var (
	Team_name = map[int32]string{
		0: "TEAM_UNSPECIFIED",
		1: "TEAM_HOME",
		2: "TEAM_AWAY",
	}
	Team_value = map[string]int32{
		"TEAM_UNSPECIFIED": 0,
		"TEAM_HOME":        1,
		"TEAM_AWAY":        2,
	}
)

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

func (x Team) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Team) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_common_team_proto_enumTypes[0].Descriptor()
}

func (Team) Type() protoreflect.EnumType {
	return &file_protocols_common_team_proto_enumTypes[0]
}

func (x Team) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Team.Descriptor instead.
func (Team) EnumDescriptor() ([]byte, []int) {
	return file_protocols_common_team_proto_rawDescGZIP(), []int{0}
}

var File_protocols_common_team_proto protoreflect.FileDescriptor

var file_protocols_common_team_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a,
	0x3a, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x45, 0x41, 0x4d, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x54, 0x45, 0x41, 0x4d, 0x5f, 0x41, 0x57, 0x41, 0x59, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protocols_common_team_proto_rawDescOnce sync.Once
	file_protocols_common_team_proto_rawDescData = file_protocols_common_team_proto_rawDesc
)

func file_protocols_common_team_proto_rawDescGZIP() []byte {
	file_protocols_common_team_proto_rawDescOnce.Do(func() {
		file_protocols_common_team_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_common_team_proto_rawDescData)
	})
	return file_protocols_common_team_proto_rawDescData
}

var file_protocols_common_team_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocols_common_team_proto_goTypes = []interface{}{
	(Team)(0), // 0: protocols.common.Team
}
var file_protocols_common_team_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocols_common_team_proto_init() }
func file_protocols_common_team_proto_init() {
	if File_protocols_common_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_common_team_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_common_team_proto_goTypes,
		DependencyIndexes: file_protocols_common_team_proto_depIdxs,
		EnumInfos:         file_protocols_common_team_proto_enumTypes,
	}.Build()
	File_protocols_common_team_proto = out.File
	file_protocols_common_team_proto_rawDesc = nil
	file_protocols_common_team_proto_goTypes = nil
	file_protocols_common_team_proto_depIdxs = nil
}
