name: Feature Request
description: Requests for new ssl-core library features.
title: "[Feature Request] Description"
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        :warning: **Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known feature request.**
  - type: textarea
    id: fr-descrip
    attributes:
      label: Describe the feature request.
      placeholder: A clear and concise description of the feature you would like, why it should be added, and any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Describe the scenario use case.
      placeholder: The capability and/or scenario usage this request supports.
    validations:
      required: true
