// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/gateway/gateway_service.proto

package gateway

import (
	common "github.com/robocin/ssl-core/playback-ms/pkg/pb/common"
	playback "github.com/robocin/ssl-core/playback-ms/pkg/pb/playback"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiveLivestreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReceiveLivestreamRequest) Reset() {
	*x = ReceiveLivestreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveLivestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveLivestreamRequest) ProtoMessage() {}

func (x *ReceiveLivestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveLivestreamRequest.ProtoReflect.Descriptor instead.
func (*ReceiveLivestreamRequest) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{0}
}

type ReceiveLivestreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sample *playback.Sample `protobuf:"bytes,1,opt,name=sample,proto3" json:"sample,omitempty"`
}

func (x *ReceiveLivestreamResponse) Reset() {
	*x = ReceiveLivestreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveLivestreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveLivestreamResponse) ProtoMessage() {}

func (x *ReceiveLivestreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveLivestreamResponse.ProtoReflect.Descriptor instead.
func (*ReceiveLivestreamResponse) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveLivestreamResponse) GetSample() *playback.Sample {
	if x != nil {
		return x.Sample
	}
	return nil
}

type GetGameEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameEventsRequest) Reset() {
	*x = GetGameEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameEventsRequest) ProtoMessage() {}

func (x *GetGameEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameEventsRequest.ProtoReflect.Descriptor instead.
func (*GetGameEventsRequest) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{2}
}

type GetGameEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameEvents []*common.GameEvent `protobuf:"bytes,1,rep,name=game_events,json=gameEvents,proto3" json:"game_events,omitempty"`
}

func (x *GetGameEventsResponse) Reset() {
	*x = GetGameEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameEventsResponse) ProtoMessage() {}

func (x *GetGameEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameEventsResponse.ProtoReflect.Descriptor instead.
func (*GetGameEventsResponse) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameEventsResponse) GetGameEvents() []*common.GameEvent {
	if x != nil {
		return x.GameEvents
	}
	return nil
}

type GetReplayChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
}

func (x *GetReplayChunkRequest) Reset() {
	*x = GetReplayChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplayChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplayChunkRequest) ProtoMessage() {}

func (x *GetReplayChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplayChunkRequest.ProtoReflect.Descriptor instead.
func (*GetReplayChunkRequest) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetReplayChunkRequest) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimestamp
	}
	return nil
}

type GetReplayChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"`
	Samples       []*playback.Sample     `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
}

func (x *GetReplayChunkResponse) Reset() {
	*x = GetReplayChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_gateway_gateway_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplayChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplayChunkResponse) ProtoMessage() {}

func (x *GetReplayChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_gateway_gateway_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplayChunkResponse.ProtoReflect.Descriptor instead.
func (*GetReplayChunkResponse) Descriptor() ([]byte, []int) {
	return file_protocols_gateway_gateway_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetReplayChunkResponse) GetLastTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTimestamp
	}
	return nil
}

func (x *GetReplayChunkResponse) GetSamples() []*playback.Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_protocols_gateway_gateway_service_proto protoreflect.FileDescriptor

var file_protocols_gateway_gateway_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a,
	0x19, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x2e,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x16,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5c, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x91, 0x01, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x07, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x2e,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x32,
	0xcf, 0x02, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x72, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x4c, 0x69, 0x76, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x62, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x28, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x61, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_gateway_gateway_service_proto_rawDescOnce sync.Once
	file_protocols_gateway_gateway_service_proto_rawDescData = file_protocols_gateway_gateway_service_proto_rawDesc
)

func file_protocols_gateway_gateway_service_proto_rawDescGZIP() []byte {
	file_protocols_gateway_gateway_service_proto_rawDescOnce.Do(func() {
		file_protocols_gateway_gateway_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_gateway_gateway_service_proto_rawDescData)
	})
	return file_protocols_gateway_gateway_service_proto_rawDescData
}

var file_protocols_gateway_gateway_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocols_gateway_gateway_service_proto_goTypes = []interface{}{
	(*ReceiveLivestreamRequest)(nil),  // 0: protocols.gateway.ReceiveLivestreamRequest
	(*ReceiveLivestreamResponse)(nil), // 1: protocols.gateway.ReceiveLivestreamResponse
	(*GetGameEventsRequest)(nil),      // 2: protocols.gateway.GetGameEventsRequest
	(*GetGameEventsResponse)(nil),     // 3: protocols.gateway.GetGameEventsResponse
	(*GetReplayChunkRequest)(nil),     // 4: protocols.gateway.GetReplayChunkRequest
	(*GetReplayChunkResponse)(nil),    // 5: protocols.gateway.GetReplayChunkResponse
	(*playback.Sample)(nil),           // 6: protocols.playback.Sample
	(*common.GameEvent)(nil),          // 7: protocols.common.GameEvent
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_protocols_gateway_gateway_service_proto_depIdxs = []int32{
	6, // 0: protocols.gateway.ReceiveLivestreamResponse.sample:type_name -> protocols.playback.Sample
	7, // 1: protocols.gateway.GetGameEventsResponse.game_events:type_name -> protocols.common.GameEvent
	8, // 2: protocols.gateway.GetReplayChunkRequest.start_timestamp:type_name -> google.protobuf.Timestamp
	8, // 3: protocols.gateway.GetReplayChunkResponse.last_timestamp:type_name -> google.protobuf.Timestamp
	6, // 4: protocols.gateway.GetReplayChunkResponse.samples:type_name -> protocols.playback.Sample
	0, // 5: protocols.gateway.GatewayService.ReceiveLivestream:input_type -> protocols.gateway.ReceiveLivestreamRequest
	2, // 6: protocols.gateway.GatewayService.GetGameEvents:input_type -> protocols.gateway.GetGameEventsRequest
	4, // 7: protocols.gateway.GatewayService.GetReplayChunk:input_type -> protocols.gateway.GetReplayChunkRequest
	1, // 8: protocols.gateway.GatewayService.ReceiveLivestream:output_type -> protocols.gateway.ReceiveLivestreamResponse
	3, // 9: protocols.gateway.GatewayService.GetGameEvents:output_type -> protocols.gateway.GetGameEventsResponse
	5, // 10: protocols.gateway.GatewayService.GetReplayChunk:output_type -> protocols.gateway.GetReplayChunkResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protocols_gateway_gateway_service_proto_init() }
func file_protocols_gateway_gateway_service_proto_init() {
	if File_protocols_gateway_gateway_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_gateway_gateway_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveLivestreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_gateway_gateway_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveLivestreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_gateway_gateway_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_gateway_gateway_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_gateway_gateway_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplayChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_gateway_gateway_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplayChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_gateway_gateway_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocols_gateway_gateway_service_proto_goTypes,
		DependencyIndexes: file_protocols_gateway_gateway_service_proto_depIdxs,
		MessageInfos:      file_protocols_gateway_gateway_service_proto_msgTypes,
	}.Build()
	File_protocols_gateway_gateway_service_proto = out.File
	file_protocols_gateway_gateway_service_proto_rawDesc = nil
	file_protocols_gateway_gateway_service_proto_goTypes = nil
	file_protocols_gateway_gateway_service_proto_depIdxs = nil
}
