// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/playback/field.proto

package playback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length                  float32 `protobuf:"fixed32,1,opt,name=length,proto3" json:"length,omitempty"`
	Width                   float32 `protobuf:"fixed32,2,opt,name=width,proto3" json:"width,omitempty"`
	GoalDepth               float32 `protobuf:"fixed32,3,opt,name=goal_depth,json=goalDepth,proto3" json:"goal_depth,omitempty"`
	GoalWidth               float32 `protobuf:"fixed32,4,opt,name=goal_width,json=goalWidth,proto3" json:"goal_width,omitempty"`
	PenaltyAreaDepth        float32 `protobuf:"fixed32,5,opt,name=penalty_area_depth,json=penaltyAreaDepth,proto3" json:"penalty_area_depth,omitempty"`
	PenaltyAreaWidth        float32 `protobuf:"fixed32,6,opt,name=penalty_area_width,json=penaltyAreaWidth,proto3" json:"penalty_area_width,omitempty"`
	BoundaryWidth           float32 `protobuf:"fixed32,7,opt,name=boundary_width,json=boundaryWidth,proto3" json:"boundary_width,omitempty"`
	GoalCenterToPenaltyMark float32 `protobuf:"fixed32,8,opt,name=goal_center_to_penalty_mark,json=goalCenterToPenaltyMark,proto3" json:"goal_center_to_penalty_mark,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_playback_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_playback_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_protocols_playback_field_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Field) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Field) GetGoalDepth() float32 {
	if x != nil {
		return x.GoalDepth
	}
	return 0
}

func (x *Field) GetGoalWidth() float32 {
	if x != nil {
		return x.GoalWidth
	}
	return 0
}

func (x *Field) GetPenaltyAreaDepth() float32 {
	if x != nil {
		return x.PenaltyAreaDepth
	}
	return 0
}

func (x *Field) GetPenaltyAreaWidth() float32 {
	if x != nil {
		return x.PenaltyAreaWidth
	}
	return 0
}

func (x *Field) GetBoundaryWidth() float32 {
	if x != nil {
		return x.BoundaryWidth
	}
	return 0
}

func (x *Field) GetGoalCenterToPenaltyMark() float32 {
	if x != nil {
		return x.GoalCenterToPenaltyMark
	}
	return 0
}

var File_protocols_playback_field_proto protoreflect.FileDescriptor

var file_protocols_playback_field_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x22, 0xb4, 0x02, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a,
	0x67, 0x6f, 0x61, 0x6c, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x67, 0x6f, 0x61, 0x6c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x6f, 0x61, 0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x67, 0x6f, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x65,
	0x6e, 0x61, 0x6c, 0x74, 0x79, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x41,
	0x72, 0x65, 0x61, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x65, 0x6e, 0x61,
	0x6c, 0x74, 0x79, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x41, 0x72, 0x65,
	0x61, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x3c, 0x0a,
	0x1b, 0x67, 0x6f, 0x61, 0x6c, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f,
	0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x17, 0x67, 0x6f, 0x61, 0x6c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x6f,
	0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x4d, 0x61, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protocols_playback_field_proto_rawDescOnce sync.Once
	file_protocols_playback_field_proto_rawDescData = file_protocols_playback_field_proto_rawDesc
)

func file_protocols_playback_field_proto_rawDescGZIP() []byte {
	file_protocols_playback_field_proto_rawDescOnce.Do(func() {
		file_protocols_playback_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_playback_field_proto_rawDescData)
	})
	return file_protocols_playback_field_proto_rawDescData
}

var file_protocols_playback_field_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocols_playback_field_proto_goTypes = []interface{}{
	(*Field)(nil), // 0: protocols.playback.Field
}
var file_protocols_playback_field_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocols_playback_field_proto_init() }
func file_protocols_playback_field_proto_init() {
	if File_protocols_playback_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_playback_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_playback_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_playback_field_proto_goTypes,
		DependencyIndexes: file_protocols_playback_field_proto_depIdxs,
		MessageInfos:      file_protocols_playback_field_proto_msgTypes,
	}.Build()
	File_protocols_playback_field_proto = out.File
	file_protocols_playback_field_proto_rawDesc = nil
	file_protocols_playback_field_proto_goTypes = nil
	file_protocols_playback_field_proto_depIdxs = nil
}
