// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/playback/raw_detection.proto

package playback

import (
	common "github.com/robocin/ssl-core/playback-ms/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawDetection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cameras []*RawDetection_Camera `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
}

func (x *RawDetection) Reset() {
	*x = RawDetection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_playback_raw_detection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDetection) ProtoMessage() {}

func (x *RawDetection) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_playback_raw_detection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDetection.ProtoReflect.Descriptor instead.
func (*RawDetection) Descriptor() ([]byte, []int) {
	return file_protocols_playback_raw_detection_proto_rawDescGZIP(), []int{0}
}

func (x *RawDetection) GetCameras() []*RawDetection_Camera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type RawDetection_Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraId uint32                       `protobuf:"varint,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	SerialId uint32                       `protobuf:"varint,2,opt,name=serial_id,json=serialId,proto3" json:"serial_id,omitempty"`
	Balls    []*RawDetection_Camera_Ball  `protobuf:"bytes,3,rep,name=balls,proto3" json:"balls,omitempty"`
	Robots   []*RawDetection_Camera_Robot `protobuf:"bytes,4,rep,name=robots,proto3" json:"robots,omitempty"`
}

func (x *RawDetection_Camera) Reset() {
	*x = RawDetection_Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_playback_raw_detection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDetection_Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDetection_Camera) ProtoMessage() {}

func (x *RawDetection_Camera) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_playback_raw_detection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDetection_Camera.ProtoReflect.Descriptor instead.
func (*RawDetection_Camera) Descriptor() ([]byte, []int) {
	return file_protocols_playback_raw_detection_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RawDetection_Camera) GetCameraId() uint32 {
	if x != nil {
		return x.CameraId
	}
	return 0
}

func (x *RawDetection_Camera) GetSerialId() uint32 {
	if x != nil {
		return x.SerialId
	}
	return 0
}

func (x *RawDetection_Camera) GetBalls() []*RawDetection_Camera_Ball {
	if x != nil {
		return x.Balls
	}
	return nil
}

func (x *RawDetection_Camera) GetRobots() []*RawDetection_Camera_Robot {
	if x != nil {
		return x.Robots
	}
	return nil
}

type RawDetection_Camera_Ball struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confidence float32          `protobuf:"fixed32,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Position   *common.Point3Df `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *RawDetection_Camera_Ball) Reset() {
	*x = RawDetection_Camera_Ball{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_playback_raw_detection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDetection_Camera_Ball) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDetection_Camera_Ball) ProtoMessage() {}

func (x *RawDetection_Camera_Ball) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_playback_raw_detection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDetection_Camera_Ball.ProtoReflect.Descriptor instead.
func (*RawDetection_Camera_Ball) Descriptor() ([]byte, []int) {
	return file_protocols_playback_raw_detection_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *RawDetection_Camera_Ball) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RawDetection_Camera_Ball) GetPosition() *common.Point3Df {
	if x != nil {
		return x.Position
	}
	return nil
}

type RawDetection_Camera_Robot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    *common.RobotId  `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Confidence float32          `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Position   *common.Point2Df `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Angle      float32          `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Height     float32          `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *RawDetection_Camera_Robot) Reset() {
	*x = RawDetection_Camera_Robot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_playback_raw_detection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawDetection_Camera_Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDetection_Camera_Robot) ProtoMessage() {}

func (x *RawDetection_Camera_Robot) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_playback_raw_detection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDetection_Camera_Robot.ProtoReflect.Descriptor instead.
func (*RawDetection_Camera_Robot) Descriptor() ([]byte, []int) {
	return file_protocols_playback_raw_detection_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *RawDetection_Camera_Robot) GetRobotId() *common.RobotId {
	if x != nil {
		return x.RobotId
	}
	return nil
}

func (x *RawDetection_Camera_Robot) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RawDetection_Camera_Robot) GetPosition() *common.Point2Df {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RawDetection_Camera_Robot) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *RawDetection_Camera_Robot) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_protocols_playback_raw_detection_proto protoreflect.FileDescriptor

var file_protocols_playback_raw_detection_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x2f, 0x72, 0x61, 0x77, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x1a, 0x1f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7,
	0x04, 0x0a, 0x0c, 0x52, 0x61, 0x77, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x41, 0x0a, 0x07, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x52, 0x61, 0x77, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x07, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x73, 0x1a, 0xf3, 0x03, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x05, 0x62, 0x61, 0x6c, 0x6c, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x52, 0x61, 0x77, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e,
	0x42, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x62, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x45, 0x0a, 0x06, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b,
	0x2e, 0x52, 0x61, 0x77, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x73, 0x1a, 0x5e, 0x0a, 0x04, 0x42, 0x61, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x44, 0x66, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0xc3, 0x01, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x34, 0x0a, 0x08,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x44, 0x66,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_playback_raw_detection_proto_rawDescOnce sync.Once
	file_protocols_playback_raw_detection_proto_rawDescData = file_protocols_playback_raw_detection_proto_rawDesc
)

func file_protocols_playback_raw_detection_proto_rawDescGZIP() []byte {
	file_protocols_playback_raw_detection_proto_rawDescOnce.Do(func() {
		file_protocols_playback_raw_detection_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_playback_raw_detection_proto_rawDescData)
	})
	return file_protocols_playback_raw_detection_proto_rawDescData
}

var file_protocols_playback_raw_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocols_playback_raw_detection_proto_goTypes = []interface{}{
	(*RawDetection)(nil),              // 0: protocols.playback.RawDetection
	(*RawDetection_Camera)(nil),       // 1: protocols.playback.RawDetection.Camera
	(*RawDetection_Camera_Ball)(nil),  // 2: protocols.playback.RawDetection.Camera.Ball
	(*RawDetection_Camera_Robot)(nil), // 3: protocols.playback.RawDetection.Camera.Robot
	(*common.Point3Df)(nil),           // 4: protocols.common.Point3Df
	(*common.RobotId)(nil),            // 5: protocols.common.RobotId
	(*common.Point2Df)(nil),           // 6: protocols.common.Point2Df
}
var file_protocols_playback_raw_detection_proto_depIdxs = []int32{
	1, // 0: protocols.playback.RawDetection.cameras:type_name -> protocols.playback.RawDetection.Camera
	2, // 1: protocols.playback.RawDetection.Camera.balls:type_name -> protocols.playback.RawDetection.Camera.Ball
	3, // 2: protocols.playback.RawDetection.Camera.robots:type_name -> protocols.playback.RawDetection.Camera.Robot
	4, // 3: protocols.playback.RawDetection.Camera.Ball.position:type_name -> protocols.common.Point3Df
	5, // 4: protocols.playback.RawDetection.Camera.Robot.robot_id:type_name -> protocols.common.RobotId
	6, // 5: protocols.playback.RawDetection.Camera.Robot.position:type_name -> protocols.common.Point2Df
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protocols_playback_raw_detection_proto_init() }
func file_protocols_playback_raw_detection_proto_init() {
	if File_protocols_playback_raw_detection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_playback_raw_detection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDetection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_playback_raw_detection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDetection_Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_playback_raw_detection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDetection_Camera_Ball); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_playback_raw_detection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawDetection_Camera_Robot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_playback_raw_detection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_playback_raw_detection_proto_goTypes,
		DependencyIndexes: file_protocols_playback_raw_detection_proto_depIdxs,
		MessageInfos:      file_protocols_playback_raw_detection_proto_msgTypes,
	}.Build()
	File_protocols_playback_raw_detection_proto = out.File
	file_protocols_playback_raw_detection_proto_rawDesc = nil
	file_protocols_playback_raw_detection_proto_goTypes = nil
	file_protocols_playback_raw_detection_proto_depIdxs = nil
}
