name: App Shell CI

on:
  pull_request:
    paths: ["app-shell/**"]
  push:
    branches: [main]
    paths: ["app-shell/**"]
  workflow_dispatch:

jobs:
  vitest:
    defaults:
      run:
        working-directory: ./app-shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g yarn && yarn
      - run: yarn test
      - uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./app-shell

  playwright-e2e:
    defaults:
      run:
        working-directory: ./app-shell
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  lighthouse-ci:
    defaults:
      run:
        working-directory: ./app-shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g yarn @lhci/cli@0.11.x && yarn
      - run: yarn build
      - run: lhci autorun
