name: "Common C++ Library: Build, Run Tests and Install"
on:
  pull_request:
    paths: ["common/cpp/**"]
  push:
    branches:
      - main
    paths: ["common/cpp/**"]
  workflow_dispatch:

jobs:
  build_run_tests_and_install:
    runs-on: ubuntu-latest
    container: robocin/ssl-core-cpp-mbed-base:latest
    strategy:
      matrix:
        cmake:
          [
            {
              compiler: arm-none-eabi-g++,
              flags: "-DCMAKE_CXX_FLAGS='--specs=nosys.specs'",
            },
            { compiler: clang++, flags: "" },
            { compiler: g++, flags: "" },
          ]
    steps:
      - uses: actions/checkout@v3
      - working-directory: common/cpp
        shell: bash
        run: |
          cmake -B build \
                -S . \
                -G Ninja \
                -DCMAKE_CXX_COMPILER=${{ matrix.cmake.compiler }} \
                ${{ matrix.cmake.flags }}
          cmake --build build
      - working-directory: common/cpp
        shell: bash
        run: |
          ctest --test-dir build
      - working-directory: common/cpp
        shell: bash
        run: |
          cmake --install build
