name: "Common C++ Library: Build, Run Tests and Install"
on:
  pull_request:
    paths: ["common/cpp/**"]
  push:
    branches:
      - main
    paths: ["common/cpp/**"]
  workflow_dispatch:

jobs:
  build_run_tests_and_install:
    runs-on: ubuntu-latest
    container: robocin/ssl-core-cpp-mbed-base:latest
    strategy:
      matrix:
        compiler:
          [
            { c: clang, cpp: clang++, flags: "" },
            { c: gcc, cpp: g++, flags: "" },
            {
              c: arm-none-eabi-gcc,
              cpp: arm-none-eabi-g++,
              flags: "-DCMAKE_C_FLAGS='--specs=nosys.specs' -DCMAKE_CXX_FLAGS='--specs=nosys.specs'",
            },
          ]
    steps:
      - uses: actions/checkout@v3
      - working-directory: common/cpp
        shell: bash
        run: |
          cmake -B build \
                -S . \
                -G Ninja \
                -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} \
                ${{ matrix.compiler.flags }}
          cmake --build build
      - working-directory: common/cpp
        shell: bash
        run: |
          ctest --test-dir build
      - working-directory: common/cpp
        shell: bash
        run: |
          cmake --install build
