name: "Gateway Augusto: Build and Run Tests"
on:
  pull_request:
    paths: ["gateway/gateway-augusto/**"]
  push:
    branches:
      - main
    paths: ["gateway/gateway-augusto/**"]
  workflow_dispatch:

env:
  cpp_compiler: clang++

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          env: cpp_compiler
          subFolder: gateway/gateway-augusto
          configFile: gateway/gateway-augusto/.devcontainer/devcontainer.json
          runCmd: |
            set -e

            ${cpp_compiler} --version

            cmake -B build \
                -S . \
                -G Ninja \
                -DCMAKE_CXX_COMPILER=${cpp_compiler}

            cmake --build build

            ctest --test-dir build

            cat non_existent_file.txt
