name: Player MFE CI

on:
  pull_request:
    paths: ["player-mfe/**"]
  push:
    branches: [main]
    paths: ["player-mfe/**"]
  workflow_dispatch:

jobs:
  vitest:
    defaults:
      run:
        working-directory: ./player-mfe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g yarn && yarn
      - run: yarn test
