version: '3'

services:
  client:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "8000:80"
    depends_on:
      - mongodb

  # redis:
  #   image: redis:latest
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"

  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"

  # cassandra:
  #   image: cassandra:latest
  #   ports:
  #     - "9042:9042"